openapi: 3.0.3
info:
  title: The SpatioTemporal Asset Catalog API - Item Collection
  description: The specification for a set of items, e.g. returned by a search.
  version: 1.0.0-beta.1
paths: {}
components:
  schemas:
    itemCollection:
      description: >-
        A GeoJSON FeatureCollection augmented with foreign members that contain values relevant to a STAC entity
      type: object
      required:
        - stac_version
        - features
        - type
      properties:
        stac_version:
          $ref: '../../core/commons.yaml#/components/schemas/stac_version'
        stac_extensions:
          $ref: '../../core/commons.yaml#/components/schemas/stac_extensions'
        type:
          type: string
          enum:
            - FeatureCollection
        features:
          type: array
          items:
            $ref: '../../core/commons.yaml#/components/schemas/item'
        links:
          type: array
          description: >-
            An array of links. Can be used for pagination, e.g. by providing a link
            with the `next` relation type.
          items:
            $ref: '../../core/commons.yaml#/components/schemas/link'
          example:
            - rel: next
              href: >-
                http://api.cool-sat.com/search?next=ANsXtp9mrqN0yrKWhf-y2PUpHRLQb1GT-mtxNcXou8TwkXhi1Jbk